# Generated by Django 2.2.3 on 2020-02-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractioninfo',
            name='source',
            field=models.CharField(choices=[('B', 'BaiDu'), ('T', 'TengXun')], default='', max_length=1, verbose_name='景区数据来源'),
            preserve_default=False,
        ),
    ]
