# Generated by Django 2.2.3 on 2020-02-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_auto_20200214_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinceinfo',
            name='province',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
