# Generated by Django 2.2.3 on 2020-02-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_auto_20200214_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='city_name',
            field=models.CharField(db_column='city', max_length=32, unique=True, verbose_name='景区所处城市名'),
        ),
    ]
